### PR TITLE
fix: in docker:go builder, path & modfile options can't be mixed

### LINKED ISSUE #1412: path and go dependencies option are not compatible
#### Version information:

current master on Intel

#### Description:

When we combine the `path` and `dependencies` options for a build, the builder can't find the modfile anymore.

Example:

```toml
# Test for https://github.com/testground/testground/issues/1357
# Introduces:
#  - `builder' option per group
#  - `path` option for generic and docker builders
[metadata]
  name = "issue-1412-path-and-go-dependencies"

[global]
  plan = "integrations_mixed_builders"
  case = "issue-1412-path-and-go-dependencies"
  total_instances = 1
  runner = "local:docker"

[[groups]]
  id = "go"
  instances = { count = 1 }
  builder = "docker:go"

  [groups.build_config]
    path = "go/"

    [[groups.build.dependencies]]
      module = "github.com/testground/sdk-go"
      version = "master"
```

Error:

```
Aug  2 11:39:33.736014  INFO    found existing volume   {"volume_name": "testground-goproxy-vol"}
Aug  2 11:39:33.775018  INFO    container is already running    {"container_name": "testground-goproxy"}
Aug  2 11:39:33.777523  INFO    build failed    {"plan": "integrations", "groups": ["go"], "builder": "docker:go", "error": "unable to add replace directives to go.mod; exit status 1; output: "}
```

### PR DESCRIPTION
**Pull request by laurentsenta**
Fix #1412

### CODE REVIEW

**Review by brdji — APPROVED** [review]

File: pkg/build/docker_go.go [hunk 1]
```diff
@@ -134,7 +134,7 @@ func (b *DockerGoBuilder) Build(ctx context.Context, in *api.BuildInput, ow *rpc
 
 	var (
 		basesrc = in.UnpackedSources.BaseDir
-		plansrc = in.UnpackedSources.PlanDir
+		planDir = in.UnpackedSources.PlanDir
 		sdksrc  = in.UnpackedSources.SDKDir
```
Comment (galargh) [inline pkg/build/docker_go.go:138]: The diff in naming convention struck me here at first. I got what's going on when I kept reading though.

**Review by galargh — APPROVED** [review]

File: pkg/build/docker_go.go (hunk 1 above)
Comment (laurentsenta) [reply pkg/build/docker_go.go:138]: That's a fair point, I'll use go convention and rename these to `baseSrc`, `planDir`, `planSrc`, `sdkSrc`

Comment (laurentsenta) [reply pkg/build/docker_go.go]: Done
